import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import * as schema from './schema';

/**
 * Opens the ledger database. WAL mode: readers never block the (single)
 * writer, and a crash mid-write can't corrupt the file — crash-only design
 * starts at the journal mode.
 */
export function openDb(path: string) {
  if (path !== ':memory:') {
    mkdirSync(dirname(path), { recursive: true });
  }
  const sqlite = new Database(path);
  sqlite.pragma('journal_mode = WAL');
  return drizzle(sqlite, { schema });
}

export type Db = ReturnType<typeof openDb>;

/**
 * Applies pending SQL migrations (generated by drizzle-kit, committed to the
 * repo). Runs at every daemon start; already-applied migrations are no-ops.
 */
export function migrateDb(db: Db, migrationsFolder: string) {
  migrate(db, { migrationsFolder });
}
