import { z } from 'zod';
import { lifecyclePolicySchema } from './policy';
import { SANDBOX_STATES } from './states';
import { templateNameSchema } from './templates';

/**
 * Caller-chosen key that acquire() is idempotent on: same key, same sandbox,
 * whatever state it was in. Opaque to the daemon; bounded so it can serve as
 * an indexed column.
 */
export const userKeySchema = z.string().min(1).max(128);

/**
 * A sandbox as reported by the daemon — the wire shape shared by the HTTP
 * API, the SDK, and the web console.
 */
export const sandboxSchema = z.object({
  /** Generated by the daemon. UUID, never a DB autoincrement — ids must stay unique across machines. */
  sandboxId: z.string(),
  userKey: userKeySchema,
  state: z.enum(SANDBOX_STATES),
  /** Machine that owns this sandbox. Single-machine today; the field keeps the ledger shardable. */
  nodeId: z.string(),
  /**
   * Base URL of the daemon that owns this sandbox. Honest limits today: it
   * is the daemon's loopback address, meaningful only on the daemon's own
   * machine — a remote caller keeps using whatever reverse-proxy address it
   * already reached the daemon through. A public-endpoint knob can land
   * when this field gains real consumers (sharding, in-sandbox exec).
   */
  endpoint: z.string(),
  policy: lifecyclePolicySchema,
  /**
   * Template the sandbox was created from; null means the daemon's base
   * image. The name is recorded, not the image it pointed at: a rebuilt
   * shell always boots the template's *current* image.
   */
  template: templateNameSchema.nullable(),
  createdAt: z.iso.datetime(),
  lastActiveAt: z.iso.datetime(),
});

export type Sandbox = z.infer<typeof sandboxSchema>;
