import { z } from 'zod';
import { lifecyclePolicySchema } from './policy';
import { SANDBOX_STATES } from './states';

/**
 * Caller-chosen key that acquire() is idempotent on: same key, same sandbox,
 * whatever state it was in. Opaque to the daemon; bounded so it can serve as
 * an indexed column.
 */
export const userKeySchema = z.string().min(1).max(128);

/**
 * A sandbox as reported by the daemon — the wire shape shared by the HTTP
 * API, the SDK, and the web console.
 */
export const sandboxSchema = z.object({
  /** Generated by the daemon. UUID, never a DB autoincrement — ids must stay unique across machines. */
  sandboxId: z.string(),
  userKey: userKeySchema,
  state: z.enum(SANDBOX_STATES),
  /** Machine that owns this sandbox. Single-machine today; the field keeps the ledger shardable. */
  nodeId: z.string(),
  /** Base URL callers use to reach this sandbox. Today always the local daemon; with sharding it may point elsewhere. */
  endpoint: z.string(),
  policy: lifecyclePolicySchema,
  createdAt: z.iso.datetime(),
  lastActiveAt: z.iso.datetime(),
});

export type Sandbox = z.infer<typeof sandboxSchema>;
