/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDomainsRouteImport } from './routes/_app/domains'
import { Route as AppDoctorRouteImport } from './routes/_app/doctor'
import { Route as AppConnectRouteImport } from './routes/_app/connect'
import { Route as AppApiKeysRouteImport } from './routes/_app/api-keys'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppSandboxesIndexRouteImport } from './routes/_app/sandboxes/index'
import { Route as AppSandboxesNameRouteImport } from './routes/_app/sandboxes/$name'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsRoute = AppDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorRoute = AppDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxesIndexRoute = AppSandboxesIndexRouteImport.update({
  id: '/sandboxes/',
  path: '/sandboxes/',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxesNameRoute = AppSandboxesNameRouteImport.update({
  id: '/sandboxes/$name',
  path: '/sandboxes/$name',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/api-keys': typeof AppApiKeysRoute
  '/connect': typeof AppConnectRoute
  '/doctor': typeof AppDoctorRoute
  '/domains': typeof AppDomainsRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/sandboxes/$name': typeof AppSandboxesNameRoute
  '/sandboxes/': typeof AppSandboxesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activity': typeof AppActivityRoute
  '/api-keys': typeof AppApiKeysRoute
  '/connect': typeof AppConnectRoute
  '/doctor': typeof AppDoctorRoute
  '/domains': typeof AppDomainsRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/': typeof AppIndexRoute
  '/sandboxes/$name': typeof AppSandboxesNameRoute
  '/sandboxes': typeof AppSandboxesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/connect': typeof AppConnectRoute
  '/_app/doctor': typeof AppDoctorRoute
  '/_app/domains': typeof AppDomainsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/sandboxes/$name': typeof AppSandboxesNameRoute
  '/_app/sandboxes/': typeof AppSandboxesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/api-keys'
    | '/connect'
    | '/doctor'
    | '/domains'
    | '/settings'
    | '/templates'
    | '/sandboxes/$name'
    | '/sandboxes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/activity'
    | '/api-keys'
    | '/connect'
    | '/doctor'
    | '/domains'
    | '/settings'
    | '/templates'
    | '/'
    | '/sandboxes/$name'
    | '/sandboxes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/activity'
    | '/_app/api-keys'
    | '/_app/connect'
    | '/_app/doctor'
    | '/_app/domains'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/'
    | '/_app/sandboxes/$name'
    | '/_app/sandboxes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains': {
      id: '/_app/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AppDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor': {
      id: '/_app/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AppDoctorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandboxes/': {
      id: '/_app/sandboxes/'
      path: '/sandboxes'
      fullPath: '/sandboxes/'
      preLoaderRoute: typeof AppSandboxesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sandboxes/$name': {
      id: '/_app/sandboxes/$name'
      path: '/sandboxes/$name'
      fullPath: '/sandboxes/$name'
      preLoaderRoute: typeof AppSandboxesNameRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppConnectRoute: typeof AppConnectRoute
  AppDoctorRoute: typeof AppDoctorRoute
  AppDomainsRoute: typeof AppDomainsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSandboxesNameRoute: typeof AppSandboxesNameRoute
  AppSandboxesIndexRoute: typeof AppSandboxesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppConnectRoute: AppConnectRoute,
  AppDoctorRoute: AppDoctorRoute,
  AppDomainsRoute: AppDomainsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppSandboxesNameRoute: AppSandboxesNameRoute,
  AppSandboxesIndexRoute: AppSandboxesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
